solve MarkedList task
js-tasks-ru/vue-20230516_katerinashatunova pull request #4
Opened 2023-06-05 19:51 UTC by kate-shatunova

2023-06-05 19:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-06-05 19:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-13 19:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-13 20:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-06-14 14:55 UTC, ShGKme requested changes
Решённая задача принята, но удаление задачи не может быть принято за её решение... Требуется решить все добавленные в PR задачи, чтобы PR был смерджен.

2023-06-18 06:15 UTC, closed without merging